In [2]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer,KNNImputer

## customer_churn.csv

In [4]:
df = pd.read_csv(r'D:\D_Drive\vamsi vs code\EDUKRON_FILES\Customer_churn_prediction_retenction\customer-churn-prediction-retention-model\Data\customer_churn.csv')

In [5]:
df.head()

  customer_id  tenure_months  ...  account_manager  updated_at
0     C000001             88  ...  Gabrielle Davis  2025-10-19
1     C000002             76  ...       Ryan Munoz  2026-03-10
2     C000003             94  ...   Monica Herrera  2026-04-05
3     C000004             84  ...     Jamie Arnold  2025-09-21
4     C000005             37  ...     Lisa Hensley  2025-07-06

[5 rows x 23 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181175 entries, 0 to 181174
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   customer_id            181175 non-null  object
 1   tenure_months          181175 non-null  int64
 2   contract_type          181175 non-null  object
 3   monthly_spend          181175 non-null  float64
 4   days_since_last_order  181175 non-null  int64
 5   support_tickets_30d    181175 non-null  int64
 6   total_spend            181175 non-null  float64
 7   order_count            181175 non-null  int64
 8   avg_order_value        181175 non-null  float64
 9   payment_method         181175 non-null  object
 10  autopay                181175 non-null  int64
 11  num_products_owned     181175 non-null  int64
 12  complaint_count        181175 non-null  int64
 13  nps_score              181175 non-null  int64
 14  satisfaction_score     181175 non-null  int64
 15  churned                181175 non-null  int64
 16  churn_reason           181175 non-null  object
 17  predicted_churn_prob   181175 non-null  float64
 18  retention_offer_sent   181175 non-null  object
 19  offer_accepted         181175 non-null  int64
 20  last_contact_date      181175 non-null  object
 21  account_manager        181175 non-null  object
 22  updated_at             181175 non-null  object
dtypes: float64(4), int64(11), object(8)
memory usage: 31.8+ MB

## campaign_responses

In [7]:
df = pd.read_csv(r'D:\D_Drive\vamsi vs code\EDUKRON_FILES\Customer_churn_prediction_retenction\customer-churn-prediction-retention-model\Data\campaign_responses.csv')

In [8]:
df.head()

  response_id campaign_id customer_id  responded  converted  revenue
0  CR00000001    CMP02950     C101095          1          0   834.66
1  CR00000002    CMP00692     C132367          1          0   571.44
2  CR00000003    CMP01635     C110361          1          1   692.89
3  CR00000004    CMP02255     C079868          0          0   276.69
4  CR00000005    CMP02561     C029179          1          1   200.92

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 578395 entries, 0 to 578394
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   response_id  578395 non-null  object
 1   campaign_id  578395 non-null  object
 2   customer_id  578395 non-null  object
 3   responded    578395 non-null  int64
 4   converted    578395 non-null  int64
 5   revenue      578395 non-null  float64
dtypes: float64(1), int64(2), object(3)
memory usage: 26.5+ MB

## customer_engagement_metrics

In [ ]:
df = pd.read_csv(r"D:\D_Drive\vamsi vs code\EDUKRON_FILES\Customer_churn_prediction_retenction\customer-churn-prediction-retention-model\Data\customer_engagement_metrics.csv")
df.head()

     metric_id customer_id  ... engagement_tier  measured_date
0  ENG00000001     C000001  ...         dormant     2025-08-20
1  ENG00000002     C000002  ...         dormant     2026-05-17
2  ENG00000003     C000003  ...             low     2025-10-12
3  ENG00000004     C000004  ...             low     2026-02-14
4  ENG00000005     C000005  ...            high     2026-02-25

[5 rows x 22 columns]

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 219231 entries, 0 to 219230
Data columns (total 22 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   metric_id                 219231 non-null  object
 1   customer_id               219231 non-null  object
 2   last_login_date           219231 non-null  object
 3   login_frequency_30d       219231 non-null  int64
 4   pages_per_session         219231 non-null  float64
 5   avg_session_duration_min  219231 non-null  float64
 6   mobile_app_usage_pct      219231 non-null  float64
 7   email_open_rate           219231 non-null  float64
 8   email_click_rate          219231 non-null  float64
 9   push_notification_opt_in  219231 non-null  int64
 10  nps_score                 219231 non-null  int64
 11  csat_score                219231 non-null  int64
 12  feature_adoption_score    219231 non-null  float64
 13  community_forum_posts     219231 non-null  int64
 14  referrals_made            219231 non-null  int64
 15  support_escalations_90d   219231 non-null  int64
 16  product_tours_completed   219231 non-null  int64
 17  wishlist_items            219231 non-null  int64
 18  cart_abandonment_rate     219231 non-null  float64
 19  promo_code_usage_90d      219231 non-null  int64
 20  engagement_tier           219231 non-null  object
 21  measured_date             219231 non-null  object
dtypes: float64(7), int64(10), object(5)
memory usage: 36.8+ MB

## customer_rfm

In [14]:
df = pd.read_csv(r"D:\D_Drive\vamsi vs code\EDUKRON_FILES\Customer_churn_prediction_retenction\customer-churn-prediction-retention-model\Data\customer_rfm.csv")
df.head()

  customer_id  recency_days  frequency  ...  f_score  m_score  rfm_segment
0     C000001           172         53  ...        3        4         Lost
1     C000002           184         50  ...        4        5          New
2     C000003           253         72  ...        1        4        Loyal
3     C000004           266          6  ...        5        2    Champions
4     C000005            34         39  ...        2        3          New

[5 rows x 8 columns]

## orders

In [15]:
df = pd.read_csv(r"D:\D_Drive\vamsi vs code\EDUKRON_FILES\Customer_churn_prediction_retenction\customer-churn-prediction-retention-model\Data\orders.csv")
df.head()

    order_id customer_id  ... fulfillment_center delivery_date
0  O00000001     C096901  ...            FC-EAST    2026-02-25
1  O00000002     C098477  ...         FC-CENTRAL    2026-03-02
2  O00000003     C038004  ...         FC-CENTRAL    2025-10-07
3  O00000004     C060257  ...         FC-CENTRAL    2026-03-25
4  O00000005     C057327  ...         FC-CENTRAL    2025-10-16

[5 rows x 23 columns]

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114387 entries, 0 to 114386
Data columns (total 23 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   order_id            114387 non-null  object
 1   customer_id         114387 non-null  object
 2   order_date          114387 non-null  object
 3   channel             114387 non-null  object
 4   total_amount        114387 non-null  float64
 5   subtotal            114387 non-null  float64
 6   tax_amount          114387 non-null  float64
 7   shipping_cost       114387 non-null  float64
 8   discount_amount     114387 non-null  float64
 9   status              114387 non-null  object
 10  payment_method      114387 non-null  object
 11  payment_last4       114387 non-null  int64
 12  shipping_country    113814 non-null  object
 13  shipping_state      114387 non-null  object
 14  shipping_city       114387 non-null  object
 15  shipping_address    114387 non-null  object
 16  billing_city        114387 non-null  object
 17  carrier             114387 non-null  object
 18  tracking_number     114387 non-null  object
 19  promo_code          85771 non-null   object
 20  is_gift             114387 non-null  int64
 21  fulfillment_center  114387 non-null  object
 22  delivery_date       114387 non-null  object
dtypes: float64(5), int64(2), object(16)
memory usage: 20.1+ MB

## subscription_billing

In [17]:
df = pd.read_csv(r"D:\D_Drive\vamsi vs code\EDUKRON_FILES\Customer_churn_prediction_retenction\customer-churn-prediction-retention-model\Data\subscription_billing.csv")
df.head()

    billing_id customer_id  ...  created_at  updated_at
0  BIL00000001     C000001  ...  2024-10-14  2025-08-20
1  BIL00000002     C000002  ...  2025-06-18  2026-05-17
2  BIL00000003     C000003  ...  2023-01-20  2025-10-12
3  BIL00000004     C000004  ...  2026-04-23  2026-02-14
4  BIL00000005     C000005  ...  2024-03-25  2026-02-25

[5 rows x 22 columns]

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126959 entries, 0 to 126958
Data columns (total 22 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   billing_id                 126959 non-null  object
 1   customer_id                126959 non-null  object
 2   plan_name                  126959 non-null  object
 3   contract_type              126959 non-null  object
 4   monthly_recurring_revenue  126959 non-null  float64
 5   annual_contract_value      126959 non-null  float64
 6   billing_cycle              126959 non-null  object
 7   payment_method             126959 non-null  object
 8   autopay_enabled            126959 non-null  int64
 9   paperless_billing          126959 non-null  int64
 10  late_payments_12m          126959 non-null  int64
 11  price_increase_last_year   126959 non-null  int64
 12  discount_pct               126959 non-null  float64
 13  tenure_months              126959 non-null  int64
 14  contract_end_date          126959 non-null  object
 15  payment_failures_90d       126959 non-null  int64
 16  billing_address_city       126959 non-null  object
 17  tax_exempt                 126959 non-null  int64
 18  invoice_delivery           126959 non-null  object
 19  account_manager            126959 non-null  object
 20  created_at                 126959 non-null  object
 21  updated_at                 126959 non-null  object
dtypes: float64(3), int64(7), object(12)
memory usage: 21.3+ MB

## support_tickets

In [19]:
df = pd.read_csv(r"D:\D_Drive\vamsi vs code\EDUKRON_FILES\Customer_churn_prediction_retenction\customer-churn-prediction-retention-model\Data\support_tickets.csv")
df.head()

  ticket_id customer_id  ... created_date resolution_time_hours
0  T0000001     C113536  ...   2026-03-02                    65
1  T0000002     C128564  ...   2025-10-07                    38
2  T0000003     C080829  ...   2026-03-25                    70
3  T0000004     C056793  ...   2025-10-16                    18
4  T0000005     C022297  ...   2025-10-19                    48

[5 rows x 10 columns]